#配置服务端口
server:
  port: 7001

spring:
  application:
    name: edu-eureka-boot #应用名称，会在Eureka中作为服务的id标识(serviceId)

#配置Eureka注册中心
eureka:
  client:
    service-url: #定义Eureka server url
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
    register-with-eureka: false #表示是否向Eureka中心注册自己的信息，因为自己就是Eureka server,所以不需要注册，默认为true
    fetch-registry: true #是否查询/拉取Eureka server服务注册列表，默认为true
  instance:
    hostname: localhost #当前Eureka实例的主机名
    #使用ip注册，否则会使用主机名注册了（此处考虑到对老版本的兼容，新版本经过实验都是ip）
    prefer-ip-address: true
    #自定义实例显示格式，加上版本号，便于多版本管理，注意是ip-address，早期版本是ipAddress
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}:@project.version@
  server:
    enable-self-preservation: true #自我保护机制，默认是：开启状态